# fly.toml app configuration file generated for 5-3-1-workout-log on 2023-09-06T16:01:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "5-3-1-workout-log"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "5-3-1-workout-log"
  DB_HOST = "aws.connect.psdb.cloud"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
